### ISSUE TITLE
Upgrade LitElement 2.0.1

### ISSUE THREAD

**Issue by hutchgrant** [ContributaryCommunity/www.contributary.community#45]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
Lit Element needs to be upgraded from @polymer/lit-element to lit-element@2.0.1

## Details
* package.json and lock files need to be updated.
* All the components need the LitElement import changed to lit-element.

**Comment by thescientist13** [comment]
@penguin999 
You mentioned looking to get more familiar with LitElement.  Maybe this might be a good issue for you take on / finish?  (see #46)
